- project:
    check: &jobs
      jobs:
        - pnpm-test:
            required-projects:
              - software-factory/re-patternfly
              - software-factory/res-remoteapi
    gate: *jobs
